### ISSUE TITLE
Can't select either 21w08b or 1.16.5 as a valid Minecraft jar in GUI mode

### ISSUE THREAD

**Issue by rjp** [tectonicus/tectonicus#154]
(Sub-issue is that GUI mode is ignoring the JAR configured in the configuration file.)

No matter where I put the client JAR, GUI mode doesn't let me use it - tested with 1.16.5.jar, 21w08b.jar in current directory, official `versions` directory, home directory, etc. Browsing doesn't let me select the `.jar` file itself but I can add it to the end of the directory in the text input.  Additionally, if I type in the path directly, it also doesn't accept it.

Happens with OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7) (default MacOS Java install) and OpenJDK Runtime Environment Zulu11.43+1007-CA (build 11.0.9.1+1-LTS) (Zulu's ARM64.)

**Comment by skoeven** [comment]
GUI mode hasn't really been maintained or updated since the project was open sourced in 2012.  The plan is to remove it and replace it with a new JavaFX gui, however that has been a low priority.  After seeing your issue I realized that the documentation still mentions GUI mode as an option so I'll go ahead and remove that so hopefully no one else tries to use it :-).
