### ISSUE TITLE
Focal length for #view signs

### ISSUE THREAD

**Issue by sentaidigital** [tectonicus/tectonicus#58]
Views created with the special #view sign are great, but they're done with such a wide-angle lens that it seriously distorts the world.  Is there some way we can change the effective focal length with a parameter on the sign?  Using equivalent mm would be perfect.  i.e, 50mm is normal, < 50mm is wide-angle, >50mm is telephoto.

**Comment by skoeven** [comment]
The FOV (Field of View) of Views can now be set in either the config xml (see the fullConfig.xml for usage) or on the View sign using the letter "f" (e.g., "#a75 h3 f60").  The FOV range is the same as Minecraft: (30-110).  I went with FOV over focal length because it is more familiar to most Minecraft players and it meant I could avoid doing a bunch of math. :-)
