### ISSUE TITLE
Add new / rearranged blocks from 1.9 (snapshot)

### ISSUE THREAD

**Issue by sentaidigital** [tectonicus/tectonicus#61]
The 1.9 snapshots are stable enough to start adding support for the new block elements.

**Comment by skoeven** [comment]
I've added all the Purpur blocks as well as the End Brick and Grass Path blocks to the defaultBlockConfig.

The End Rod, Chaos Plant/Flower, Frosted Ice, and Command Blocks would each require a new blockType which means I may hold off on these until I get the new Block Model rendering system in place.

Redstone wire rendering is currently broken because they changed the textures for some unfathomable reason.  The new Block Model system may help resolve this as well.

**Comment by turtle2472** [comment]
Have I missed the compiled version of this?  I'm still seeing 2.20 as the current version.

**Comment by skoeven** [comment]
I hadn't had time until this weekend to get a new release out.  It's up now: [https://github.com/tectonicus/tectonicus/releases/tag/v2.21](https://github.com/tectonicus/tectonicus/releases/tag/v2.21)

**Comment by skoeven** [comment]
I've just uploaded [v2.22](https://github.com/tectonicus/tectonicus/releases/tag/v2.22) which adds all the blocks I said I wasn't going to add yet. :-)  Redstone wire is also fixed.
I think I've got them all in there now, but let me know if I've missed any new blocks.
