### ISSUE TITLE
Guide for headless Linux machine to render maps

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#86]
I have searched and search but not found a good guide on setting this up in a headless environment on a modern (CentOS 7) linux machine.  Is there a good guide out there to building a machine to run the maps headless?

**Comment by skoeven** [comment]
The only guide I know of is the one on the Minecraft wiki: [http://minecraft.gamepedia.com/Programs_and_editors/Tectonicus/VPS#RHEL.2FCentOS_5_.28and_likely_other_RPM_based_distributions.29](http://minecraft.gamepedia.com/Programs_and_editors/Tectonicus/VPS#RHEL.2FCentOS_5_.28and_likely_other_RPM_based_distributions.29)
It says it's for CentOS 5 so it might take some tweaking to make it work with CentOS 7.

**Comment by skoeven** [comment]
I managed to get it working by adapting the directions for Ubuntu 11.10 which uses vnc server. [http://minecraft.gamepedia.com/Programs_and_editors/Tectonicus/VPS#Ubuntu_11.10_oneiric_64_bit](http://minecraft.gamepedia.com/Programs_and_editors/Tectonicus/VPS#Ubuntu_11.10_oneiric_64_bit)

Use yum instead of apt-get:
`sudo yum install vnc-server`

Then create a shell script like the following:
<pre>vncserver :1
export DISPLAY=:1
java -jar Tectonicus.jar config=config.xml
vncserver -kill :1
export DISPLAY=
</pre>

**Comment by turtle2472** [comment]
I'm building a VM to test this in now.  I just need to make a minimal config.xml since my normal one takes days to do the initial render.  Thank you very much for there still being caching, otherwise I wouldn't be able to do my maps with this.  Our world is huge (compared to how small we used to keep it at least.)

**Comment by turtle2472** [comment]
So it won't work on a CentOS Minimal install but worked on my Everything install.  I'll run with that for now.  I don't care to take the time to figure out what packages I need to install for Minimal to work.  Thanks!  My crons can live again!
