### ISSUE TITLE
Long render times, missing block and a few minor questions

### ISSUE THREAD

**Issue by xm8** [tectonicus/tectonicus#91]
Hello,

first of all, thanks for this great tool.

1. FYI, there are 2 missing blocks /errors while rendering with 2.24:
The texture file 'assets/minecraft/textures/blocks/bed_head_top.png' could not be found.
Error while parsing blockConfig element: [Bed: null]

The texture file 'assets/minecraft/textures/blocks/usb_charger_side.png' could not be found.
Error while parsing blockConfig element: [Solid: null]

2nd obviously from the 1. April update, but still in the 2.24 version.

2. I have a Map with 855.000 Chunks (about 1,4Mio tiles)
Rendering the first 1 Mio Tiles, on the first zoom level, goes pretty fast, maybe 20h.
But the last 400k take then extra 30-40h.
Is there any known reason for that ?

My render System:
CPU: i7 3770 4x 3,4Ghz
RAM: 16 GB DDR3 - 1600MHz
OpenGL Vendor: Intel
OpenGL Renderer: Intel(R) HD Graphics 4000
OpenGL Version: 4.0.0 - Build 10.18.10.4425

I dedicated 8 Threads and 14GB of RAM to the render progress.
CPU is only 15-20 in usage.

- 2.1 Whats the bottleneck in the render progress and does the graphic card can help ?

Cause my main System has:
CPU: i7 - 4930K 6x 3,4GHz (12 Threads)
RAM: 32GB  DDR3 - 2133MHz
2x GTX1080

But i dont want it to render also 30-40 hours :D , then i rather prefer the render-PC beeing busy with that.

3. Suggestion:

- It would be amazing for big Maps, if i could connect already rendered parts.
Sometimes we are located in a radius of 5-10k Blocks for weeks/months, so there would be no need to render again a whole radius of 30-40k.
But ofc we want to see the map in total.
Maybe this is already possible with copy paste and im just to stupid to understand it ? :-D

Hope u can help us.

Thank you in advance !

**Comment by turtle2472** [comment]
Do you use caching?  My world is pretty big with 1,123,109 chunks.  Total render time for 7 layers is about 2 hours and 10 minutes without any changes.  With changes it is longer, though I have it on a cron to update the maps every 6 hours.  This is in a Cent OS 7 VM with 3 cores (i7-6700K) and 12GB of RAM assigned. I do have 3D graphics enabled on the VM, it is GTX 750 Ti .

Be sure to use `useCache = "true"` in your Tectonicus config xml.

It takes me a full 70 hours or more to do a complete new render.

**Comment by xm8** [comment]
Thanks for ur reply. :)

1. useCache is on "true"

What do u mean without changes? Do i have to change to just update a map ? o.O
Normally i just drag and drop the new world dir and start rendering.
Updating a map would be much more easy for me.

How excactly does it work ?

Thanks in advance.

**Comment by turtle2472** [comment]
I'm just guessing, but I think because you replace your world folder with the copy each time it changes enough that Tectonicus thinks it is a new render and forces a complete start.  Near the top of the tectonics.log look for something like "World changes, creating new cache" or something like that.  

When I said without any changes, I mean that no one played the server between renders.  Sure the initial chunk always has changes, but it is minor and really fast to render.  The "with changes" part is players actually doing things in other chunks on the server.  My server isn't extremely active.

My process is to use rsync to update only the world files that changed.  I sync the files from my world folder to a local folder for the map generation.  Then it looks for the changes file in the world only. `rsync -avczP -e "ssh -i /home/me/.ssh/me-rsync-key" --delete me@192.168.x.x:/opt/minecraft/backups/world/ $worldfolder`

I use linux for all my MC related gear.  The game server, the Tectonicus server and the web server too.

**Comment by xm8** [comment]
Thanks for ur reply again.

So yes, i have a "changed.log" so i guess ur right about that and i`ll test ist out with few changes and see if render will still take like forever.

But there is one thing i dont understand.
Why should i render a map twice when nobody has played it between those 2 render dates ?
There shouldnt be any differences in the Output anyways.
Or did i missunderstand?

to ur 3. Part:
I Use Microsoft, but nevermind, i`ll work it out that the map will be synced. If it works then i`ll just have to check how smart tectonicus is in identifying the same file, cause when i overwrite it, then the "creation date" will change. Hope tec. is smart enough for that, i`ll see :D

**Comment by turtle2472** [comment]
Mine renders via cron job every 6 hours no matter if anyone has played or not.  That is why I notice it.  By automating the process, small changes don't build up into massive map updates.  This this many chunks, they more frequent the updates the less rendering that will be needed.  Plus, if a rendering fails for any reason (computer reboot, drive full, alien abduction, etc...) then when it does render again there will be less to update.  Since I have 7 layers, this is a really big deal for my map.

For Windows, you might look at using an FTP client to sync the changed files.  I know some of them will only copy changed files, this might be faster for you.

**Comment by FireflyHM** [comment]
I too have issues with extremely long render times. After some testing on two separate computers, I have come to the following conclusion:

Number of tiles to render increases with map size. What is not so obvious is that for every single tile rendered, there exists a corresponding tile hash in one of the cache directories. When you have several million tiny hash files all in the same directory (1 directory per layer), the IO costs incurred to work with the cache becomes absurdly high. You end up spending far more time waiting for the IO operations to complete than actually doing useful work. This is especially true if your storage is not local, e.g. instead of a HDD/SSD in your computer, your map data is being stored on a NAS. Furthermore, each hash file is only a few hundred bytes at most (can't remember the exact size), and most (if not all) modern computer systems have a minimum disk cluster size of 4 kilobytes, resulting in extreme disk space wastage.

The above observation holds true for many of the other directories used by the cache system as well. All in all, if you have a world that is of a relatively large size, disabling the cache may yield significantly faster results and smaller disk space usage than having it enabled. This defeats the point of having the cache system completely, and is not a good solution either since you are being forced to render the entire map each time.

This software is a great piece of work and I thank the author(s) for making it. But the caching system is in dire need of a complete revamp to something that doesn't end up with millions of tiny files. Some sort of database system needs to be implemented.

**Comment by skoeven** [comment]
I've made a change (d7548c90c2fa31abd109e069f30a81fddb717e3e) to now use the H2 MVStore to cache the tile hashes.  This creates a single file for each layer which should resolve the filesystem performance and storage issues previously caused by the tile hash files.  The other files in the Cache directory are much less of a concern.  Those files are used during rendering and downsampling and setting useCache to false has no effect on them.
