### ISSUE TITLE
Generated sites doesn't work through proxy with SSL enabled

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#94]
I made a change in my networking stack and added a reverse proxy (nginx) that serves encrypted frontend.

While this isn't an issue with Tectonicus directly, I'm wondering if a config flag could be added to allow this kind of support.

I also have a number of archived maps that don't work this way so at the least it would be nice to be able to edit them.  I haven't searched how to modify the old maps to work through the reverse proxy with https frontend yet, but I just discovered the issue and am beginning to work through it.  If you know what files I need to manually modify for those it would be awesome and help me out a lot if you would post the details here.  I'm not much of a coder so learning as I go.

**Comment by skoeven** [comment]
I'm don't know for sure, but it might be an issue with the Google Maps API.  I was already planning on getting rid of Google Maps because of some changes that they are making to how it can be used, but it's not going to be a simple project to switch over to Leaflet or something else.
I'll see what I can do this summer, but I have a bunch of life changes coming up (getting married) so unfortunately I don't know how much time I'll have to work on Tectonicus.

**Comment by turtle2472** [comment]
I found out it is actually an internal network issue.  Seems others outside of my network see it fine, it's an issue on my side though.  So really, this could be closed.

On the other note I sure do hope you don't continue building/maintaining Tectonicus.  I totally understand life moving on though.  If nothing else I want you to know me and my players totally appreciate all the work you have put into this even if you never update it again.

Congratulations on the coming wedding!
